//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYS.FORMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3")]
        public string SYS_FORMS_nfce_pr_homologacao_autorizacao_NfeAutorizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_homologacao_autorizacao_NfeAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeRetAutorizacao3")]
        public string SYS_FORMS_nfce_pr_homologacao_consultaRecibo_NfeRetAutorizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_homologacao_consultaRecibo_NfeRetAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeConsulta3")]
        public string SYS_FORMS_nfce_pr_homologacao_consultaChaveAcesso_NfeConsulta3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_homologacao_consultaChaveAcesso_NfeConsulta3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeInutilizacao3")]
        public string SYS_FORMS_nfce_pr_homologacao_inutilizacao_NfeInutilizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_homologacao_inutilizacao_NfeInutilizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeStatusServico3")]
        public string SYS_FORMS_nfce_pr_homologacao_consultaStatusServico_NfeStatusServico3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_homologacao_consultaStatusServico_NfeStatusServico3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeRecepcaoEvento")]
        public string SYS_FORMS_nfce_pr_homologacao_registroEvento_RecepcaoEvento {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_homologacao_registroEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3")]
        public string SYS_FORMS_nfce_pr_producao_autorizacao_NfeAutorizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_producao_autorizacao_NfeAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeRetAutorizacao3")]
        public string SYS_FORMS_nfce_pr_producao_consultaRecibo_NfeRetAutorizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_producao_consultaRecibo_NfeRetAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeConsulta3")]
        public string SYS_FORMS_nfce_pr_producao_consultaChaveAcesso_NfeConsulta3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_producao_consultaChaveAcesso_NfeConsulta3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeInutilizacao3")]
        public string SYS_FORMS_nfce_pr_producao_inutilizacao_NfeInutilizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_producao_inutilizacao_NfeInutilizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeStatusServico3")]
        public string SYS_FORMS_nfce_pr_producao_consultaStatusServico_NfeStatusServico3 {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_producao_consultaStatusServico_NfeStatusServico3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeRecepcaoEvento")]
        public string SYS_FORMS_nfce_pr_producao_registroEvento_RecepcaoEvento {
            get {
                return ((string)(this["SYS_FORMS_nfce_pr_producao_registroEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeAutorizacao3")]
        public string SYS_FORMS_nfe_pr_homologacao_autorizacao_NfeAutorizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_homologacao_autorizacao_NfeAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeRetAutorizacao3")]
        public string SYS_FORMS_nfe_pr_homologacao_consultaRecibo_NfeRetAutorizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_homologacao_consultaRecibo_NfeRetAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeConsulta3")]
        public string SYS_FORMS_nfe_pr_homologacao_consultaChaveAcesso_NfeConsulta3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_homologacao_consultaChaveAcesso_NfeConsulta3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeInutilizacao3")]
        public string SYS_FORMS_nfe_pr_homologacao_inutilizacao_NfeInutilizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_homologacao_inutilizacao_NfeInutilizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeStatusServico3")]
        public string SYS_FORMS_nfe_pr_homologacao_consultaStatusServico_NfeStatusServico3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_homologacao_consultaStatusServico_NfeStatusServico3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/CadConsultaCadastro2")]
        public string SYS_FORMS_nfe_pr_homologacao_consultaCadastro_CadConsultaCadastro2 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_homologacao_consultaCadastro_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeRecepcaoEvento")]
        public string SYS_FORMS_nfe_pr_homologacao_registroEvento_RecepcaoEvento {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_homologacao_registroEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.pr.gov.br/nfe/NFeAutorizacao3")]
        public string SYS_FORMS_nfe_pr_producao_autorizacao_NfeAutorizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_producao_autorizacao_NfeAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.pr.gov.br/nfe/NFeRetAutorizacao3")]
        public string SYS_FORMS_nfe_pr_producao_consultaRecibo_NfeRetAutorizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_producao_consultaRecibo_NfeRetAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.pr.gov.br/nfe/NFeConsulta3")]
        public string SYS_FORMS_nfe_pr_producao_consultaChaveAcesso_NfeConsulta3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_producao_consultaChaveAcesso_NfeConsulta3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.pr.gov.br/nfe/NFeInutilizacao3")]
        public string SYS_FORMS_nfe_pr_producao_inutilizacao_NfeInutilizacao3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_producao_inutilizacao_NfeInutilizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.pr.gov.br/nfe/NFeStatusServico3")]
        public string SYS_FORMS_nfe_pr_producao_consultaStatusServico_NfeStatusServico3 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_producao_consultaStatusServico_NfeStatusServico3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.pr.gov.br/nfe/CadConsultaCadastro2")]
        public string SYS_FORMS_nfe_pr_producao_consultaCadastro_CadConsultaCadastro2 {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_producao_consultaCadastro_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.pr.gov.br/nfe/NFeRecepcaoEvento")]
        public string SYS_FORMS_nfe_pr_producao_registroEvento_RecepcaoEvento {
            get {
                return ((string)(this["SYS_FORMS_nfe_pr_producao_registroEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente")]
        public string SYS_FORMS_correios_AtendeClienteService {
            get {
                return ((string)(this["SYS_FORMS_correios_AtendeClienteService"]));
            }
        }
    }
}
