using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SYS.QUERYS.Cadastros.Financeiro
{
    public class QMoeda
    {
        public List<MMoeda> UFs
        {
            get
            {
                return new List<MMoeda>
                {
                    new MMoeda { ID_MOEDA = 005, NM = "AFEGANE AFEGANIST" },
                    new MMoeda { ID_MOEDA = 008, NM = "BIRR" },
                    new MMoeda { ID_MOEDA = 009, NM = "BIRR/ETIOPIA" },
                    new MMoeda { ID_MOEDA = 010, NM = "AUSTRAL" },
                    new MMoeda { ID_MOEDA = 015, NM = "BATH/TAILANDIA" },
                    new MMoeda { ID_MOEDA = 020, NM = "BALBOA/PANAMA" },
                    new MMoeda { ID_MOEDA = 025, NM = "BOLIVAR/VENZUELA" },
                    new MMoeda { ID_MOEDA = 026, NM = "BOLIVAR VEN" },
                    new MMoeda { ID_MOEDA = 030, NM = "BOLIVIANO/BOLIVIA" },
                    new MMoeda { ID_MOEDA = 035, NM = "CEDI GANA" },
                    new MMoeda { ID_MOEDA = 040, NM = "COLON/COSTA RICA" },
                    new MMoeda { ID_MOEDA = 045, NM = "COLON/EL SALVADOR" },
                    new MMoeda { ID_MOEDA = 050, NM = "CORDOBA/NICARAGUA" },
                    new MMoeda { ID_MOEDA = 051, NM = "CORDOBA OURO" },
                    new MMoeda { ID_MOEDA = 055, NM = "COROA DINAM/DINAM" },
                    new MMoeda { ID_MOEDA = 057, NM = "COROA ESTONIA" },
                    new MMoeda { ID_MOEDA = 058, NM = "COROA ESLOVACA" },
                    new MMoeda { ID_MOEDA = 060, NM = "COROA ISLND/ISLAN" },
                    new MMoeda { ID_MOEDA = 065, NM = "COROA NORUE/NORUE" },
                    new MMoeda { ID_MOEDA = 070, NM = "COROA SUECA/SUECI" },
                    new MMoeda { ID_MOEDA = 075, NM = "COROA TCHECA" },
                    new MMoeda { ID_MOEDA = 078, NM = "CRUZADO NOVO" },
                    new MMoeda { ID_MOEDA = 079, NM = "CRUZADO" },
                    new MMoeda { ID_MOEDA = 080, NM = "CRUZEIRO" },
                    new MMoeda { ID_MOEDA = 083, NM = "CRUZEIRO" },
                    new MMoeda { ID_MOEDA = 085, NM = "CRUZEIRO REAL" },
                    new MMoeda { ID_MOEDA = 088, NM = "CUPON GEORGIANO" },
                    new MMoeda { ID_MOEDA = 090, NM = "DALASI/GAMBIA" },
                    new MMoeda { ID_MOEDA = 095, NM = "DINAR ARGELINO" },
                    new MMoeda { ID_MOEDA = 100, NM = "DINAR/KWAIT" },
                    new MMoeda { ID_MOEDA = 105, NM = "DINAR/BAHREIN" },
                    new MMoeda { ID_MOEDA = 110, NM = "DINAR IEMENITA" },
                    new MMoeda { ID_MOEDA = 115, NM = "DINAR/IRAQUE" },
                    new MMoeda { ID_MOEDA = 120, NM = "DINAR IUGOSLAVO" },
                    new MMoeda { ID_MOEDA = 125, NM = "DINAR/JORDANIA" },
                    new MMoeda { ID_MOEDA = 130, NM = "DINAR/LIBIA" },
                    new MMoeda { ID_MOEDA = 132, NM = "DINAR/MACEDONIA" },
                    new MMoeda { ID_MOEDA = 133, NM = "DINAR SERVIO SERV" },
                    new MMoeda { ID_MOEDA = 134, NM = "NOVA LIBRA SUDANE" },
                    new MMoeda { ID_MOEDA = 135, NM = "DINAR/TUNISIA" },
                    new MMoeda { ID_MOEDA = 138, NM = "DIREITO ESPECIAL" },
                    new MMoeda { ID_MOEDA = 139, NM = "DIRHAM/MARROCOS" },
                    new MMoeda { ID_MOEDA = 145, NM = "DIRHAM/EMIR ARABE" },
                    new MMoeda { ID_MOEDA = 148, NM = "DOBRA S TOME PRIN" },
                    new MMoeda { ID_MOEDA = 150, NM = "DOLAR AUSTRALIANO" },
                    new MMoeda { ID_MOEDA = 155, NM = "DOLAR/BAHAMAS" },
                    new MMoeda { ID_MOEDA = 160, NM = "DOLAR/BERMUDAS" },
                    new MMoeda { ID_MOEDA = 165, NM = "DOLAR CANADENSE" },
                    new MMoeda { ID_MOEDA = 170, NM = "DOLAR DA GUIANA" },
                    new MMoeda { ID_MOEDA = 173, NM = "DOLAR DA NAMIBIA" },
                    new MMoeda { ID_MOEDA = 175, NM = "DOLAR/BARBADOS" },
                    new MMoeda { ID_MOEDA = 180, NM = "DOLAR/BELIZE" },
                    new MMoeda { ID_MOEDA = 185, NM = "DOLAR BRUNEI" },
                    new MMoeda { ID_MOEDA = 190, NM = "DOLAR/CAYMAN" },
                    new MMoeda { ID_MOEDA = 195, NM = "DOLAR CINGAPURA" },
                    new MMoeda { ID_MOEDA = 200, NM = "DOLAR FIJI" },
                    new MMoeda { ID_MOEDA = 205, NM = "DOLAR HONG KONG" },
                    new MMoeda { ID_MOEDA = 210, NM = "DOLAR/TRIN TOBAG" },
                    new MMoeda { ID_MOEDA = 215, NM = "DOLAR CARIBE ORIE" },
                    new MMoeda { ID_MOEDA = 217, NM = "DOLAR ZIMBABUE" },
                    new MMoeda { ID_MOEDA = 220, NM = "DOLAR DOS EUA" },
                    new MMoeda { ID_MOEDA = 225, NM = "DOLAR/ETIOPIA" },
                    new MMoeda { ID_MOEDA = 230, NM = "DOLAR/JAMAICA" },
                    new MMoeda { ID_MOEDA = 235, NM = "DOLAR LIBERIA" },
                    new MMoeda { ID_MOEDA = 240, NM = "DOLAR MALAIO" },
                    new MMoeda { ID_MOEDA = 245, NM = "DOLAR/NOVA ZELAND" },
                    new MMoeda { ID_MOEDA = 250, NM = "DOLAR IL SALOMAO" },
                    new MMoeda { ID_MOEDA = 255, NM = "DOLAR/SURINAME" },
                    new MMoeda { ID_MOEDA = 260, NM = "DONGUE/VIETNAN" },
                    new MMoeda { ID_MOEDA = 270, NM = "DRACMA/GRECIA" },
                    new MMoeda { ID_MOEDA = 275, NM = "DRAM ARMENIA REP" },
                    new MMoeda { ID_MOEDA = 295, NM = "ESCUDO CABO VERDE" },
                    new MMoeda { ID_MOEDA = 315, NM = "ESCUDO PORTUGUES" },
                    new MMoeda { ID_MOEDA = 320, NM = "ESCUDO TIMOR LEST" },
                    new MMoeda { ID_MOEDA = 325, NM = "GUILDER ANTILHAS" },
                    new MMoeda { ID_MOEDA = 328, NM = "FLORIM/ARUBA" },
                    new MMoeda { ID_MOEDA = 330, NM = "FLORIM/SURINAME" },
                    new MMoeda { ID_MOEDA = 333, NM = "DOLAR/SURINAME" },
                    new MMoeda { ID_MOEDA = 335, NM = "FLORIM HOLANDES" },
                    new MMoeda { ID_MOEDA = 345, NM = "FORINT/HUNGRIA" },
                    new MMoeda { ID_MOEDA = 360, NM = "FRANCO BELGA/BELG" },
                    new MMoeda { ID_MOEDA = 361, NM = "FRANCO BELGA FINA" },
                    new MMoeda { ID_MOEDA = 363, NM = "FRANCO CONGOLES" },
                    new MMoeda { ID_MOEDA = 365, NM = "FRANCO/BURUNDI" },
                    new MMoeda { ID_MOEDA = 368, NM = "FRANCO/COMORES" },
                    new MMoeda { ID_MOEDA = 370, NM = "FRANCO CFA BEAC" },
                    new MMoeda { ID_MOEDA = 372, NM = "FRANCO CFA BCEAO" },
                    new MMoeda { ID_MOEDA = 380, NM = "FRANCO CFP" },
                    new MMoeda { ID_MOEDA = 385, NM = "FRANCO/BURUNDI" },
                    new MMoeda { ID_MOEDA = 390, NM = "FRANCO/DJIBUTI" },
                    new MMoeda { ID_MOEDA = 395, NM = "FRANCO FRANCES" },
                    new MMoeda { ID_MOEDA = 398, NM = "FRANCO/GUINE" },
                    new MMoeda { ID_MOEDA = 400, NM = "FRANCO LUXEMBURGO" },
                    new MMoeda { ID_MOEDA = 405, NM = "FRANCO MALGAXE MA" },
                    new MMoeda { ID_MOEDA = 406, NM = "ARIARY MADAGASCAR" },
                    new MMoeda { ID_MOEDA = 410, NM = "FRANCO MALI" },
                    new MMoeda { ID_MOEDA = 420, NM = "FRANCO/RUANDA" },
                    new MMoeda { ID_MOEDA = 425, NM = "FRANCO SUICO" },
                    new MMoeda { ID_MOEDA = 440, NM = "GOURDE/HAITI" },
                    new MMoeda { ID_MOEDA = 450, NM = "GUARANI/PARAGUAI" },
                    new MMoeda { ID_MOEDA = 460, NM = "HRYVNIA UCRANIA" },
                    new MMoeda { ID_MOEDA = 470, NM = "ZIENE" },
                    new MMoeda { ID_MOEDA = 480, NM = "INTI PERUANO" },
                    new MMoeda { ID_MOEDA = 482, NM = "LARI GEORGIA" },
                    new MMoeda { ID_MOEDA = 485, NM = "LAT/LETONIA REP" },
                    new MMoeda { ID_MOEDA = 490, NM = "LEK ALBANIA REP" },
                    new MMoeda { ID_MOEDA = 495, NM = "LEMPIRA/HONDURAS" },
                    new MMoeda { ID_MOEDA = 500, NM = "LEONE/SERRA LEOA" },
                    new MMoeda { ID_MOEDA = 503, NM = "LEU/MOLDAVIA REP" },
                    new MMoeda { ID_MOEDA = 505, NM = "LEU/ROMENIA" },
                    new MMoeda { ID_MOEDA = 506, NM = "NOVO LEU/ROMENIA" },
                    new MMoeda { ID_MOEDA = 510, NM = "LEV/BULGARIA REP" },
                    new MMoeda { ID_MOEDA = 520, NM = "LIBRA CIP/CHIPRE" },
                    new MMoeda { ID_MOEDA = 530, NM = "LIBRA/GIBRALTAR" },
                    new MMoeda { ID_MOEDA = 535, NM = "LIBRA/EGITO" },
                    new MMoeda { ID_MOEDA = 540, NM = "LIBRA ESTERLINA" },
                    new MMoeda { ID_MOEDA = 545, NM = "LIBRA/FALKLAND" },
                    new MMoeda { ID_MOEDA = 550, NM = "LIBRA/IRLANDA" },
                    new MMoeda { ID_MOEDA = 555, NM = "LIBRA ISRAELENSE" },
                    new MMoeda { ID_MOEDA = 560, NM = "LIBRA/LIBANO" },
                    new MMoeda { ID_MOEDA = 565, NM = "LIRA/MALTA" },
                    new MMoeda { ID_MOEDA = 570, NM = "LIBRA/STA HELENA" },
                    new MMoeda { ID_MOEDA = 575, NM = "LIBRA/SIRIA REP" },
                    new MMoeda { ID_MOEDA = 580, NM = "LIBRA SUDANESA" },
                    new MMoeda { ID_MOEDA = 585, NM = "LILANGENI/SUAZIL" },
                    new MMoeda { ID_MOEDA = 595, NM = "LIRA ITALIANA" },
                    new MMoeda { ID_MOEDA = 600, NM = "LIRA/TURQUIA" },
                    new MMoeda { ID_MOEDA = 601, NM = "LITA/LITUANIA" },
                    new MMoeda { ID_MOEDA = 603, NM = "LOTI/LESOTO" },
                    new MMoeda { ID_MOEDA = 605, NM = "MARCO" },
                    new MMoeda { ID_MOEDA = 607, NM = "MANAT ARZEBAIJAO" },
                    new MMoeda { ID_MOEDA = 608, NM = "NOVO MANAT TURCOM" },
                    new MMoeda { ID_MOEDA = 610, NM = "MARCO ALEMAO" },
                    new MMoeda { ID_MOEDA = 612, NM = "MARCO CONV BOSNIA" },
                    new MMoeda { ID_MOEDA = 615, NM = "MARCO FINLANDES" },
                    new MMoeda { ID_MOEDA = 620, NM = "METICAL MOCAMBIQ" },
                    new MMoeda { ID_MOEDA = 622, NM = "NOVA METICAL/MOCA" },
                    new MMoeda { ID_MOEDA = 625, NM = "NAKFA ERITREIA" },
                    new MMoeda { ID_MOEDA = 630, NM = "NAIRA/NIGERIA" },
                    new MMoeda { ID_MOEDA = 635, NM = "KWANZA/ANGOLA" },
                    new MMoeda { ID_MOEDA = 637, NM = "NOVO DINAR IUGOSL" },
                    new MMoeda { ID_MOEDA = 640, NM = "NOVO DOLAR/TAIWAN" },
                    new MMoeda { ID_MOEDA = 642, NM = "NOVA LIRA/TURQUIA" },
                    new MMoeda { ID_MOEDA = 645, NM = "NOVO PESO/MEXICO" },
                    new MMoeda { ID_MOEDA = 646, NM = "NOVO PESO/MEXICO" },
                    new MMoeda { ID_MOEDA = 650, NM = "NOVO PESO URUGUAI" },
                    new MMoeda { ID_MOEDA = 651, NM = "NOVO PESO URUGUAI" },
                    new MMoeda { ID_MOEDA = 660, NM = "NOVO SOL/PERU" },
                    new MMoeda { ID_MOEDA = 663, NM = "NOVO ZAIRE/ZAIRE" },
                    new MMoeda { ID_MOEDA = 665, NM = "NGULTRUM/BUTAO" },
                    new MMoeda { ID_MOEDA = 670, NM = "UGUIA MAURITANIA" },
                    new MMoeda { ID_MOEDA = 680, NM = "PAANGA/TONGA" },
                    new MMoeda { ID_MOEDA = 685, NM = "PATACA/MACAU" },
                    new MMoeda { ID_MOEDA = 690, NM = "PESETA/ANDORA" },
                    new MMoeda { ID_MOEDA = 700, NM = "PESETA ESPANHOLA" },
                    new MMoeda { ID_MOEDA = 705, NM = "PESO ARGENTINO" },
                    new MMoeda { ID_MOEDA = 706, NM = "PESO/ARGENTINA" },
                    new MMoeda { ID_MOEDA = 710, NM = "PESO BOLIVIANO" },
                    new MMoeda { ID_MOEDA = 715, NM = "PESO CHILE" },
                    new MMoeda { ID_MOEDA = 720, NM = "PESO/COLOMBIA" },
                    new MMoeda { ID_MOEDA = 725, NM = "PESO/CUBA" },
                    new MMoeda { ID_MOEDA = 730, NM = "PESO/REP DOMINIC" },
                    new MMoeda { ID_MOEDA = 735, NM = "PESO/FILIPINAS" },
                    new MMoeda { ID_MOEDA = 738, NM = "PESO/GUINE BISSAU" },
                    new MMoeda { ID_MOEDA = 740, NM = "PESO MEXICANO" },
                    new MMoeda { ID_MOEDA = 741, NM = "PESO/MEXICO" },
                    new MMoeda { ID_MOEDA = 745, NM = "PESO/URUGUAIO" },
                    new MMoeda { ID_MOEDA = 755, NM = "PULA/BOTSWANA" },
                    new MMoeda { ID_MOEDA = 760, NM = "QUACHA/MALAVI" },
                    new MMoeda { ID_MOEDA = 765, NM = "QUACHA ZAMBIA" },
                    new MMoeda { ID_MOEDA = 766, NM = "QUACHA ZAMBIA" },
                    new MMoeda { ID_MOEDA = 770, NM = "QUETZAL/GUATEMALA" },
                    new MMoeda { ID_MOEDA = 775, NM = "QUIATE/BIRMANIA" },
                    new MMoeda { ID_MOEDA = 776, NM = "KARBOVANETS" },
                    new MMoeda { ID_MOEDA = 778, NM = "KINA/PAPUA N GUIN" },
                    new MMoeda { ID_MOEDA = 779, NM = "KUNA/CROACIA" },
                    new MMoeda { ID_MOEDA = 780, NM = "QUIPE/LAOS REP" },
                    new MMoeda { ID_MOEDA = 785, NM = "RANDE/AFRICA SUL" },
                    new MMoeda { ID_MOEDA = 790, NM = "REAL BRASIL" },
                    new MMoeda { ID_MOEDA = 795, NM = "RENMIMBI IUAN" },
                    new MMoeda { ID_MOEDA = 796, NM = "RENMINBI HONG KON" },
                    new MMoeda { ID_MOEDA = 800, NM = "RIAL/CATAR" },
                    new MMoeda { ID_MOEDA = 805, NM = "RIAL/OMA" },
                    new MMoeda { ID_MOEDA = 810, NM = "RIAL/IEMEN" },
                    new MMoeda { ID_MOEDA = 815, NM = "RIAL/IRAN REP" },
                    new MMoeda { ID_MOEDA = 820, NM = "RIAL/ARAB SAUDITA" },
                    new MMoeda { ID_MOEDA = 825, NM = "RIEL/CAMBOJA" },
                    new MMoeda { ID_MOEDA = 828, NM = "RINGGIT/MALASIA" },
                    new MMoeda { ID_MOEDA = 829, NM = "RUBLO BELARUS" },
                    new MMoeda { ID_MOEDA = 830, NM = "RUBLO/RUSSIA" },
                    new MMoeda { ID_MOEDA = 835, NM = "SOMONI TADJIQUIST" },
                    new MMoeda { ID_MOEDA = 840, NM = "RUPIA/MAURICIO" },
                    new MMoeda { ID_MOEDA = 845, NM = "RUPIA/NEPAL" },
                    new MMoeda { ID_MOEDA = 850, NM = "RUPIA/SEYCHELES" },
                    new MMoeda { ID_MOEDA = 855, NM = "RUPIA/SRI LANKA" },
                    new MMoeda { ID_MOEDA = 860, NM = "RUPIA/INDIA" },
                    new MMoeda { ID_MOEDA = 865, NM = "RUPIA/INDONESIA" },
                    new MMoeda { ID_MOEDA = 870, NM = "RUFIA/MALDIVAS" },
                    new MMoeda { ID_MOEDA = 875, NM = "RUPIA/PAQUISTAO" },
                    new MMoeda { ID_MOEDA = 880, NM = "SHEKEL/ISRAEL" },
                    new MMoeda { ID_MOEDA = 890, NM = "SOL PERUANO" },
                    new MMoeda { ID_MOEDA = 892, NM = "SOM QUIRGUISTAO" },
                    new MMoeda { ID_MOEDA = 893, NM = "SOM UZBEQUISTAO" },
                    new MMoeda { ID_MOEDA = 895, NM = "SUCRE EQUADOR" },
                    new MMoeda { ID_MOEDA = 905, NM = "TACA/BANGLADESH" },
                    new MMoeda { ID_MOEDA = 910, NM = "TALA" },
                    new MMoeda { ID_MOEDA = 911, NM = "TALA SAMOA OC" },
                    new MMoeda { ID_MOEDA = 913, NM = "TENGE CAZAQUISTAO" },
                    new MMoeda { ID_MOEDA = 914, NM = "TOLAR/ESLOVENIA" },
                    new MMoeda { ID_MOEDA = 915, NM = "TUGRIK/MONGOLIA" },
                    new MMoeda { ID_MOEDA = 916, NM = "UNID FOMENTO CHIL" },
                    new MMoeda { ID_MOEDA = 918, NM = "UNID MONET EUROP" },
                    new MMoeda { ID_MOEDA = 920, NM = "VATU VANUATU" },
                    new MMoeda { ID_MOEDA = 925, NM = "WON/COREIA NORTE" },
                    new MMoeda { ID_MOEDA = 930, NM = "WON COREIA SUL" },
                    new MMoeda { ID_MOEDA = 940, NM = "XELIM AUSTRIACO" },
                    new MMoeda { ID_MOEDA = 945, NM = "XELIM DA TANZANIA" },
                    new MMoeda { ID_MOEDA = 946, NM = "XELIM/TANZANIA" },
                    new MMoeda { ID_MOEDA = 950, NM = "XELIM/QUENIA" },
                    new MMoeda { ID_MOEDA = 955, NM = "XELIM/UGANDA" },
                    new MMoeda { ID_MOEDA = 960, NM = "XELIM/SOMALIA" },
                    new MMoeda { ID_MOEDA = 970, NM = "NOVO ZAIRE ZAIRE" },
                    new MMoeda { ID_MOEDA = 971, NM = "NOVO ZAIRE/ZAIRE" },
                    new MMoeda { ID_MOEDA = 975, NM = "ZLOTY/POLONIA" },
                    new MMoeda { ID_MOEDA = 978, NM = "EURO" },
                    new MMoeda { ID_MOEDA = 980, NM = "DOLAR-EX-ALEM ORI" },
                    new MMoeda { ID_MOEDA = 982, NM = "DOLAR-BULGARIA" },
                    new MMoeda { ID_MOEDA = 983, NM = "DOLAR-GRECIA" },
                    new MMoeda { ID_MOEDA = 984, NM = "DOLAR-HUNGRIA" },
                    new MMoeda { ID_MOEDA = 986, NM = "DOLAR-ISRAEL" },
                    new MMoeda { ID_MOEDA = 988, NM = "DOLAR-IUGOSLAVIA" },
                    new MMoeda { ID_MOEDA = 990, NM = "DOLAR-POLONIA" },
                    new MMoeda { ID_MOEDA = 991, NM = "PRATA-DEAFI" },
                    new MMoeda { ID_MOEDA = 992, NM = "DOLAR-ROMENIA" },
                    new MMoeda { ID_MOEDA = 993, NM = "PALADIO" },
                    new MMoeda { ID_MOEDA = 994, NM = "PLATINA" },
                    new MMoeda { ID_MOEDA = 995, NM = "BUA" },
                    new MMoeda { ID_MOEDA = 996, NM = "FUA" },
                    new MMoeda { ID_MOEDA = 998, NM = "DOLAR OURO" }
                };
            }
        }
    }

    public class MMoeda
    {
        public int ID_MOEDA { get; set; }
        public string NM { get; set; }
    }
}
