using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SYS.QUERYS.Cadastros.Fiscal
{
    public class QEnquadramento
    {
        public List<MClasseEnquadramento> ClassesEnquadramento
        {
            get
            {
                return new List<MClasseEnquadramento>
                {
                    new MClasseEnquadramento { ID = "I", NM = "Cigarros; 24022000; Art. 153 do Decreto 4.544/2002 ou Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "II", NM = "Cigarros; 24022000; Art. 153 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "III-M", NM = "Cigarros; 24022000; Art. 153 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "III-R", NM = "Cigarros; 24022000; Art. 153 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "IV-M", NM = "Cigarros; 24022000; Art. 153 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "IV-R", NM = "Cigarros; 24022000; Art. 153 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "A", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "B", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "C", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "D", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "E", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "F", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "G", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "H", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "J", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "K", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "L", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "M", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "N", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "O", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "P", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "Q", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "R", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "S", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "T", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "U", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "V", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "X", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "Y", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "Z", NM = "Bebidas \"Quentes\"; 2204 / 2205 / 2206 / 2208; Art. 149 do Decreto 4.544/2002" },
                    new MClasseEnquadramento { ID = "99999", NM = "Outros produtos" }
                };
            }
        }

        public List<MEnquadramento> Enquadramentos
        {
            get
            {
                return new List<MEnquadramento>
                {
                    new MEnquadramento { ID = "001", GRUPO = "IMUNIDADE", NM = "LIVROS, JORNAIS, PERIÓDICOS E O PAPEL DESTINADO À SUA IMPRESSÃO - ART. 18 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "002", GRUPO = "IMUNIDADE", NM = "PRODUTOS INDUSTRIALIZADOS DESTINADOS AO EXTERIOR - ART. 18 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "003", GRUPO = "IMUNIDADE", NM = "OURO, DEFINIDO EM LEI COMO ATIVO FINANCEIRO OU INSTRUMENTO CAMBIAL - ART. 18 INCISO III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "004", GRUPO = "IMUNIDADE", NM = "ENERGIA ELÉTRICA, DERIVADOS DE PETRÓLEO, COMBUSTÍVEIS E MINERAIS DO PAÍS - ART. 18 INCISO IV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "005", GRUPO = "IMUNIDADE", NM = "EXPORTAÇÃO DE PRODUTOS NACIONAIS - SEM SAÍDA DO TERRITÓRIO BRASILEIRO - VENDA PARA EMPRESA SEDIADA NO EXTERIOR - ATIVIDADES DE PESQUISA OU LAVRA DE JAZIDAS DE PETRÓLEO E DE GÁS NATURAL - ART. 19 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "006", GRUPO = "IMUNIDADE", NM = "EXPORTAÇÃO DE PRODUTOS NACIONAIS - SEM SAÍDA DO TERRITÓRIO BRASILEIRO - VENDA PARA EMPRESA SEDIADA NO EXTERIOR - INCORPORADOS A PRODUTO FINAL EXPORTADO PARA O BRASIL - ART. 19 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "007", GRUPO = "IMUNIDADE", NM = "EXPORTAÇÃO DE PRODUTOS NACIONAIS - SEM SAÍDA DO TERRITÓRIO BRASILEIRO - VENDA PARA ÓRGÃO OU ENTIDADE DE GOVERNO ESTRANGEIRO OU ORGANISMO INTERNACIONAL DE QUE O BRASIL SEJA MEMBRO, PARA SER ENTREGUE, NO PAÍS, À ORDEM DO COMPRADOR - ART. 19 INCISO III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "101", GRUPO = "SUSPENSÃO", NM = "ÓLEO DE MENTA EM BRUTO, PRODUZIDO POR LAVRADORES - ART. 43 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "102", GRUPO = "SUSPENSÃO", NM = "PRODUTOS REMETIDOS À EXPOSIÇÃO EM FEIRAS DE AMOSTRAS E PROMOÇÕES SEMELHANTES - ART. 43 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "103", GRUPO = "SUSPENSÃO", NM = "PRODUTOS REMETIDOS A DEPÓSITOS FECHADOS OU ARMAZÉNS-GERAIS, BEM ASSIM AQUELES DEVOLVIDOS AO REMETENTE - ART. 43 INCISO III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "104", GRUPO = "SUSPENSÃO", NM = "PRODUTOS INDUSTRIALIZADOS, QUE COM MATÉRIAS-PRIMAS (MP), PRODUTOS INTERMEDIÁRIOS (PI) E MATERIAL DE EMBALAGEM (ME) IMPORTADOS SUBMETIDOS A REGIME ADUANEIRO ESPECIAL (DRAWBACK - SUSPENSÃO/ISENÇÃO), REMETIDOS DIRETAMENTE A EMPRESAS INDUSTRIAIS EXPORTADORAS - ART. 43 INCISO IV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "105", GRUPO = "SUSPENSÃO", NM = "PRODUTOS, DESTINADOS À EXPORTAÇÃO, QUE SAIAM DO ESTABELECIMENTO INDUSTRIAL PARA EMPRESAS COMERCIAIS EXPORTADORAS, COM O FIM ESPECÍFICO DE EXPORTAÇÃO - ART. 43, INCISO V, ALÍNEA \"A\" DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "106", GRUPO = "SUSPENSÃO", NM = "PRODUTOS, DESTINADOS À EXPORTAÇÃO, QUE SAIAM DO ESTABELECIMENTO INDUSTRIAL PARA RECINTOS ALFANDEGADOS ONDE SE PROCESSE O DESPACHO ADUANEIRO DE EXPORTAÇÃO - ART. 43, INCISO V, ALÍNEAS \"B\" DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "107", GRUPO = "SUSPENSÃO", NM = "PRODUTOS, DESTINADOS À EXPORTAÇÃO, QUE SAIAM DO ESTABELECIMENTO INDUSTRIAL PARA OUTROS LOCAIS ONDE SE PROCESSE O DESPACHO ADUANEIRO DE EXPORTAÇÃO - ART. 43, INCISO V, ALÍNEAS \"C\" DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "108", GRUPO = "SUSPENSÃO", NM = "MATÉRIAS-PRIMAS (MP), PRODUTOS INTERMEDIÁRIOS (PI) E MATERIAL DE EMBALAGEM (ME) DESTINADOS AO EXECUTOR DE INDUSTRIALIZAÇÃO POR ENCOMENDA - ART. 43 INCISO VI DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "109", GRUPO = "SUSPENSÃO", NM = "PRODUTOS INDUSTRIALIZADOS POR ENCOMENDA REMETIDOS AO ESTABELECIMENTO DE ORIGEM - ART. 43 INCISO VII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "110", GRUPO = "SUSPENSÃO", NM = "MATÉRIAS-PRIMAS OU PRODUTOS INTERMEDIÁRIOS REMETIDOS PARA EMPREGO EM OPERAÇÃO INDUSTRIAL REALIZADA PELO REMETENTE FORA DO ESTABELECIMENTO - ART. 43 INCISO VIII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "111", GRUPO = "SUSPENSÃO", NM = "VEÍCULO, AERONAVE OU EMBARCAÇÃO DESTINADOS A EMPREGO EM PROVAS DE ENGENHARIA PELO FABRICANTE - ART. 43 INCISO IX DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "112", GRUPO = "SUSPENSÃO", NM = "PRODUTOS REMETIDOS, PARA INDUSTRIALIZAÇÃO OU COMÉRCIO, DE UM PARA OUTRO ESTABELECIMENTO DA MESMA FIRMA - ART. 43 INCISO X DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "113", GRUPO = "SUSPENSÃO", NM = "BENS DO ATIVO PERMANENTE REMETIDOS A OUTRO ESTABELECIMENTO DA MESMA FIRMA, PARA SEREM UTILIZADOS NO PROCESSO INDUSTRIAL DO RECEBEDOR - ART. 43 INCISO XI DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "114", GRUPO = "SUSPENSÃO", NM = "BENS DO ATIVO PERMANENTE REMETIDOS A OUTRO ESTABELECIMENTO, PARA SEREM UTILIZADOS NO PROCESSO INDUSTRIAL DE PRODUTOS ENCOMENDADOS PELO REMETENTE - ART. 43 INCISO XII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "115", GRUPO = "SUSPENSÃO", NM = "PARTES E PEÇAS DESTINADAS AO REPARO DE PRODUTOS COM DEFEITO DE FABRICAÇÃO, QUANDO A OPERAÇÃO FOR EXECUTADA GRATUITAMENTE, EM VIRTUDE DE GARANTIA - ART. 43 INCISO XIII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "116", GRUPO = "SUSPENSÃO", NM = "MATÉRIAS-PRIMAS (MP), PRODUTOS INTERMEDIÁRIOS (PI) E MATERIAL DE EMBALAGEM (ME) DE FABRICAÇÃO NACIONAL, VENDIDOS A ESTABELECIMENTO INDUSTRIAL, PARA INDUSTRIALIZAÇÃO DE PRODUTOS DESTINADOS À EXPORTAÇÃO OU A ESTABELECIMENTO COMERCIAL, PARA INDUSTRIALIZAÇÃO EM OUTRO ESTABELECIMENTO DA MESMA FIRMA OU DE TERCEIRO, DE PRODUTO DESTINADO À EXPORTAÇÃO - ART. 43 INCISO XIV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "117", GRUPO = "SUSPENSÃO", NM = "PRODUTOS PARA EMPREGO OU CONSUMO NA INDUSTRIALIZAÇÃO OU ELABORAÇÃO DE PRODUTO A SER EXPORTADO, ADQUIRIDOS NO MERCADO INTERNO OU IMPORTADOS - ART. 43 INCISO XV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "118", GRUPO = "SUSPENSÃO", NM = "BEBIDAS ALCÓOLICAS E DEMAIS PRODUTOS DE PRODUÇÃO NACIONAL ACONDICIONADOS EM RECIPIENTES DE CAPACIDADE SUPERIOR AO LIMITE MÁXIMO PERMITIDO PARA VENDA A VAREJO - ART. 44 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "119", GRUPO = "SUSPENSÃO", NM = "PRODUTOS CLASSIFICADOS NCM 21.06.90.10 EX 02, 22.01, 22.02, EXCETO OS EX 01 E EX 02 DO CÓDIGO 22.02.90.00 E 22.03 SAÍDOS DE ESTABELECIMENTO INDUSTRIAL DESTINADO A COMERCIAL EQUIPARADO A INDUSTRIAL - ART. 45 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "120", GRUPO = "SUSPENSÃO", NM = "PRODUTOS CLASSIFICADOS NCM 21.06.90.10 EX 02, 22.01, 22.02, EXCETO OS EX 01 E EX 02 DO CÓDIGO 22.02.90.00 E 22.03 SAÍDOS DE ESTABELECIMENTO COMERCIAL EQUIPARADO A INDUSTRIAL DESTINADO A EQUIPARADO A INDUSTRIAL - ART. 45 INCISO II DO DECRETO7.212/2010" },
                    new MEnquadramento { ID = "121", GRUPO = "SUSPENSÃO", NM = "PRODUTOS CLASSIFICADOS NCM 21.06.90.10 EX 02, 22.01, 22.02, EXCETO OS EX 01 E EX 02 DO CÓDIGO 22.02.90.00 E 22.03 SAÍDOS DE IMPORTADOR DESTINADO A EQUIPARADO A INDUSTRIAL - ART. 45 INCISO III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "122", GRUPO = "SUSPENSÃO", NM = "MATÉRIAS-PRIMAS (MP), PRODUTOS INTERMEDIÁRIOS (PI) E MATERIAL DE EMBALAGEM (ME) DESTINADOS A ESTABELECIMENTO QUE SE DEDIQUE À ELABORAÇÃO DE PRODUTOS CLASSIFICADOS NOS CÓDIGOS PREVISTOS NO ART. 25 DA LEI 10.684/2003 - ART. 46 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "123", GRUPO = "SUSPENSÃO", NM = "MATÉRIAS-PRIMAS (MP), PRODUTOS INTERMEDIÁRIOS (PI) E MATERIAL DE EMBALAGEM (ME) ADQUIRIDOS POR ESTABELECIMENTOS INDUSTRIAIS FABRICANTES DE PARTES E PEÇAS DESTINADAS A ESTABELECIMENTO INDUSTRIAL FABRICANTE DE PRODUTO CLASSIFICADO NO CAPÍTULO 88 DA TIPI - ART. 46 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "124", GRUPO = "SUSPENSÃO", NM = "MATÉRIAS-PRIMAS (MP), PRODUTOS INTERMEDIÁRIOS (PI) E MATERIAL DE EMBALAGEM (ME) ADQUIRIDOS POR PESSOAS JURÍDICAS PREPONDERANTEMENTE EXPORTADORAS - ART. 46 INCISO III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "125", GRUPO = "SUSPENSÃO", NM = "MATERIAIS E EQUIPAMENTOS DESTINADOS A EMBARCAÇÕES PRÉ-REGISTRADAS OU REGISTRADAS NO REGISTRO ESPECIAL BRASILEIRA - REB QUANDO ADQUIRIDOS POR ESTALEIROS NAVAIS BRASILEIROS - ART. 46 INCISO IV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "126", GRUPO = "SUSPENSÃO", NM = "AQUISIÇÃO POR BENEFICIÁRIO DE REGIME ADUANEIRO SUSPENSIVO DO IMPOSTO, DESTINADO A INDUSTRIALIZAÇÃO PARA EXPORTAÇÃO - ART. 47 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "127", GRUPO = "SUSPENSÃO", NM = "DESEMBARAÇO DE PRODUTOS DE PROCEDÊNCIA ESTRANGEIRA IMPORTADOS POR LOJAS FRANCAS - ART. 48 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "128", GRUPO = "SUSPENSÃO", NM = "DESEMBARAÇO DE MAQUINAS, EQUIPAMENTOS, VEÍCULOS, APARELHOS E INSTRUMENTOS SEM SIMILAR NACIONAL IMPORTADOS POR EMPRESAS NACIONAIS DE ENGENHARIA, DESTINADOS À EXECUÇÃO DE OBRAS NO EXTERIOR - ART. 48 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "129", GRUPO = "SUSPENSÃO", NM = "DESEMBARAÇO DE PRODUTOS DE PROCEDÊNCIA ESTRANGEIRA COM SAÍDA DE REPARTIÇÕES ADUANEIRAS COM SUSPENSÃO DO IMPOSTO DE IMPORTAÇÃO - ART. 48 INCISO III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "130", GRUPO = "SUSPENSÃO", NM = "DESEMBARAÇO DE MATÉRIAS-PRIMAS, PRODUTOS INTERMEDIÁRIOS E MATERIAIS DE EMBALAGEM, IMPORTADOS DIRETAMENTE POR ESTABELECIMENTO DE QUE TRATAM OS INCISOS I A III DO CAPUT DO DECRETO 7.212/2010 - ART. 48 INCISO IV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "131", GRUPO = "SUSPENSÃO", NM = "REMESSA DE PRODUTOS PARA A ZFM DESTINADOS AO SEU CONSUMO INTERNO, UTILIZAÇÃO OU INDUSTRIALIZAÇÃO - ART. 84 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "132", GRUPO = "SUSPENSÃO", NM = "REMESSA DE PRODUTOS PARA A ZFM DESTINADOS À EXPORTAÇÃO - ART. 85 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "133", GRUPO = "SUSPENSÃO", NM = "PRODUTOS QUE, ANTES DE SUA REMESSA À ZFM, FOREM ENVIADOS PELO SEU FABRICANTE A OUTRO ESTABELECIMENTO, PARA INDUSTRIALIZAÇÃO ADICIONAL, POR CONTA E ORDEM DO DESTINATÁRIO - ART. 85 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "134", GRUPO = "SUSPENSÃO", NM = "DESEMBARAÇO DE PRODUTOS DE PROCEDÊNCIA ESTRANGEIRA IMPORTADOS PELA ZFM QUANDO ALI CONSUMIDOS OU UTILIZADOS, EXCETO ARMAS, MUNIÇÕES, FUMO, BEBIDAS ALCOÓLICAS E AUTOMÓVEIS DE PASSAGEIROS. - ART. 86 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "135", GRUPO = "SUSPENSÃO", NM = "REMESSA DE PRODUTOS PARA A AMAZÔNIA OCIDENTAL DESTINADOS AO SEU CONSUMO INTERNO OU UTILIZAÇÃO - ART. 96 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "136", GRUPO = "SUSPENSÃO", NM = "ENTRADA DE PRODUTOS ESTRANGEIROS NA ÁREA DE LIVRE COMÉRCIO DE TABATINGA - ALCT DESTINADOS AO SEU CONSUMO INTERNO OU UTILIZAÇÃO - ART. 106 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "137", GRUPO = "SUSPENSÃO", NM = "ENTRADA DE PRODUTOS ESTRANGEIROS NA ÁREA DE LIVRE COMÉRCIO DE GUAJARÁ-MIRIM - ALCGM DESTINADOS AO SEU CONSUMO INTERNO OU UTILIZAÇÃO - ART. 109 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "138", GRUPO = "SUSPENSÃO", NM = "ENTRADA DE PRODUTOS ESTRANGEIROS NAS ÁREAS DE LIVRE COMÉRCIO DE BOA VISTA - ALCBV E BOMFIM - ALCB DESTINADOS A SEU CONSUMO INTERNO OU UTILIZAÇÃO - ART. 112 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "139", GRUPO = "SUSPENSÃO", NM = "ENTRADA DE PRODUTOS ESTRANGEIROS NA ÁREA DE LIVRE COMÉRCIO DE MACAPÁ E SANTANA - ALCMS DESTINADOS A SEU CONSUMO INTERNO OU UTILIZAÇÃO - ART. 116 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "140", GRUPO = "SUSPENSÃO", NM = "ENTRADA DE PRODUTOS ESTRANGEIROS NAS ÁREAS DE LIVRE COMÉRCIO DE BRASILÉIA - ALCB E DE CRUZEIRO DO SUL - ALCCS DESTINADOS A SEU CONSUMO INTERNO OU UTILIZAÇÃO - ART. 119 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "141", GRUPO = "SUSPENSÃO", NM = "REMESSA PARA ZONA DE PROCESSAMENTO DE EXPORTAÇÃO - ZPE - ART. 121 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "142", GRUPO = "SUSPENSÃO", NM = "SETOR AUTOMOTIVO - DESEMBARAÇO ADUANEIRO, CHASSIS E OUTROS - REGIME ADUANEIRO ESPECIAL - INDUSTRIALIZAÇÃO 87.01 A 87.05 - ART. 136, I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "143", GRUPO = "SUSPENSÃO", NM = "SETOR AUTOMOTIVO - DO ESTABELECIMENTO INDUSTRIAL PRODUTOS 87.01 A 87.05 DA TIPI - MERCADO INTERNO - EMPRESA COMERCIAL ATACADISTA CONTROLADA POR PJ ENCOMENDANTE DO EXTERIOR. - ART." },
                    new MEnquadramento { ID = "136", GRUPO = "SUSPENSÃO", NM = "ENTRADA DE PRODUTOS ESTRANGEIROS NA ÁREA DE LIVRE COMÉRCIO DE TABATINGA - ALCT DESTINADOS AO SEU CONSUMO INTERNO OU UTILIZAÇÃO - ART. 106 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "144", GRUPO = "SUSPENSÃO", NM = "SETOR AUTOMOTIVO - DO ESTABELECIMENTO INDUSTRIAL - CHASSIS E OUTROS CLASSIFICADOS NAS POSIÇÕES 84.29, 84.32, 84.33, 87.01 A 87.06 E 87.11 DA TIPI. - ART. 136, III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "145", GRUPO = "SUSPENSÃO", NM = "SETOR AUTOMOTIVO - DESEMBARAÇO ADUANEIRO, CHASSIS E OUTROS CLASSIFICADOS NAS POSIÇÕES 84.29, 84.32, 84.33, 87.01 A 87.06 E 87.11 DA TIPI QUANDO IMPORTADOS DIRETAMENTE POR ESTABELECIMENTO INDUSTRIAL - ART. 136, IV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "146", GRUPO = "SUSPENSÃO", NM = "SETOR AUTOMOTIVO - DO ESTABELECIMENTO INDUSTRIAL MATÉRIAS-PRIMAS, OS PRODUTOS INTERMEDIÁRIOS E OS MATERIAIS DE EMBALAGEM, ADQUIRIDOS POR FABRICANTES, PREPONDERANTEMENTE, DE COMPONENTES, CHASSIS E OUTROS CLASSIFICADOS NOS CÓDIGOS 84.29, 8432.40.00, 8432.80.00, 8433.20, 8433.30.00, 8433.40.00, 8433.5 E 87.01 A 87.06 DA TIPI - ART. 136, V DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "147", GRUPO = "SUSPENSÃO", NM = "SETOR AUTOMOTIVO - DESEMBARAÇO ADUANEIRO, AS MATÉRIAS-PRIMAS, OS PRODUTOS INTERMEDIÁRIOS E OS MATERIAIS DE EMBALAGEM, IMPORTADOS DIRETAMENTE POR FABRICANTES, PREPONDERANTEMENTE, DE COMPONENTES, CHASSIS E OUTROS CLASSIFICADOS NOS CÓDIGOS 84.29, 8432.40.00, 8432.80.00, 8433.20, 8433.30.00, 8433.40.00, 8433.5 E 87.01 A 87.06 DA TIPI - ART. 136, VI DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "148", GRUPO = "SUSPENSÃO", NM = "BENS DE INFORMÁTICA E AUTOMAÇÃO - MATÉRIAS-PRIMAS, OS PRODUTOS INTERMEDIÁRIOS E OS MATERIAIS DE EMBALAGEM, QUANDO ADQUIRIDOS POR ESTABELECIMENTOS INDUSTRIAIS FABRICANTES DOS REFERIDOS BENS. - ART. 148 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "149", GRUPO = "SUSPENSÃO", NM = "REPORTO - SAÍDA DE ESTABELECIMENTO DE MÁQUINAS E OUTROS QUANDO ADQUIRIDOS POR BENEFICIÁRIOS DO REPORTO - ART. 166, I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "150", GRUPO = "SUSPENSÃO", NM = "REPORTO - DESEMBARAÇO ADUANEIRO DE MÁQUINAS E OUTROS QUANDO ADQUIRIDOS POR BENEFICIÁRIOS DO REPORTO - ART. 166, II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "151", GRUPO = "SUSPENSÃO", NM = "REPES - DESEMBARAÇO ADUANEIRO - BENS SEM SIMILAR NACIONAL IMPORTADOS POR BENEFICIÁRIOS DO REPES - ART. 171 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "152", GRUPO = "SUSPENSÃO", NM = "RECINE - SAÍDA PARA BENEFICIÁRIO DO REGIME - ART. 14, III DA LEI 12.599/2012" },
                    new MEnquadramento { ID = "153", GRUPO = "SUSPENSÃO", NM = "RECINE - DESEMBARAÇO ADUANEIRO POR BENEFICIÁRIO DO REGIME - ART. 14, IV DA LEI 12.599/2012" },
                    new MEnquadramento { ID = "154", GRUPO = "SUSPENSÃO", NM = "REIF - SAÍDA PARA BENEFICIÁRIO DO REGIME - LEI 12.794/1013, ART. 8, III" },
                    new MEnquadramento { ID = "155", GRUPO = "SUSPENSÃO", NM = "REIF - DESEMBARAÇO ADUANEIRO POR BENEFICIÁRIO DO REGIME - LEI 12.794/1013, ART. 8, IV" },
                    new MEnquadramento { ID = "156", GRUPO = "SUSPENSÃO", NM = "REPNBL-REDES - SAÍDA PARA BENEFICIÁRIO DO REGIME - LEI Nº 12.715/2012, ART. 30, II" },
                    new MEnquadramento { ID = "157", GRUPO = "SUSPENSÃO", NM = "RECOMPE - SAÍDA DE MATÉRIAS-PRIMAS E PRODUTOS INTERMEDIÁRIOS PARA BENEFICIÁRIOS DO REGIME - DECRETO Nº 7.243/2010, ART. 5º, I" },
                    new MEnquadramento { ID = "158", GRUPO = "SUSPENSÃO", NM = "RECOMPE - SAÍDA DE MATÉRIAS-PRIMAS E PRODUTOS INTERMEDIÁRIOS DESTINADOS A INDUSTRIALIZAÇÃO DE EQUIPAMENTOS - PROGRAMA ESTÍMULO UNIVERSIDADE-EMPRESA - APOIO À INOVAÇÃO - DECRETO Nº 7.243/2010, ART. 5º, III" },
                    new MEnquadramento { ID = "159", GRUPO = "SUSPENSÃO", NM = "RIO 2016 - PRODUTOS NACIONAIS, DURÁVEIS, USO E CONSUMO DOS EVENTOS, ADQUIRIDOS PELAS PESSOAS JURÍDICAS MENCIONADAS NO § 2O DO ART. 4O DA LEI Nº 12.780/2013 - LEI Nº 12.780/2013, ART. 13" },
                    new MEnquadramento { ID = "301", GRUPO = "ISENÇÃO", NM = "PRODUTOS INDUSTRIALIZADOS POR INSTITUIÇÕES DE EDUCAÇÃO OU DE ASSISTÊNCIA SOCIAL, DESTINADOS A USO PRÓPRIO OU A DISTRIBUIÇÃO GRATUITA A SEUS EDUCANDOS OU ASSISTIDOS - ART. 54 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "302", GRUPO = "ISENÇÃO", NM = "PRODUTOS INDUSTRIALIZADOS POR ESTABELECIMENTOS PÚBLICOS E AUTÁRQUICOS DA UNIÃO, DOS ESTADOS, DO DISTRITO FEDERAL E DOS MUNICÍPIOS, NÃO DESTINADOS A COMÉRCIO - ART. 54 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "303", GRUPO = "ISENÇÃO", NM = "AMOSTRAS DE PRODUTOS PARA DISTRIBUIÇÃO GRATUITA, DE DIMINUTO OU NENHUM VALOR COMERCIAL - ART. 54 INCISO III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "304", GRUPO = "ISENÇÃO", NM = "AMOSTRAS DE TECIDOS SEM VALOR COMERCIAL - ART. 54 INCISO IV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "305", GRUPO = "ISENÇÃO", NM = "PÉS ISOLADOS DE CALÇADOS - ART. 54 INCISO V DO DECRETO 7.212/2010 " },
                    new MEnquadramento { ID = "306", GRUPO = "ISENÇÃO", NM = "AERONAVES DE USO MILITAR E SUAS PARTES E PEÇAS, VENDIDAS À UNIÃO - ART. 54 INCISO VI DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "307", GRUPO = "ISENÇÃO", NM = "CAIXÕES FUNERÁRIOS - ART. 54 INCISO VII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "308", GRUPO = "ISENÇÃO", NM = "PAPEL DESTINADO À IMPRESSÃO DE MÚSICAS - ART. 54 INCISO VIII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "309", GRUPO = "ISENÇÃO", NM = "PANELAS E OUTROS ARTEFATOS SEMELHANTES, DE USO DOMÉSTICO, DE FABRICAÇÃO RÚSTICA, DE PEDRA OU BARRO BRUTO - ART. 54 INCISO IX DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "310", GRUPO = "ISENÇÃO", NM = "CHAPÉUS, ROUPAS E PROTEÇÃO, DE COURO, PRÓPRIOS PARA TROPEIROS - ART. 54 INCISO X DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "311", GRUPO = "ISENÇÃO", NM = "MATERIAL BÉLICO, DE USO PRIVATIVO DAS FORÇAS ARMADAS, VENDIDO À UNIÃO - ART. 54 INCISO XI DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "312", GRUPO = "ISENÇÃO", NM = "AUTOMÓVEL ADQUIRIDO DIRETAMENTE A FABRICANTE NACIONAL, PELAS MISSÕES DIPLOMÁTICAS E REPARTIÇÕES CONSULARES DE CARÁTER PERMANENTE, OU SEUS INTEGRANTES, BEM ASSIM PELAS REPRESENTAÇÕES INTERNACIONAIS OU REGIONAIS DE QUE O BRASIL SEJA MEMBRO, E SEUS FUNCIONÁRIOS, PERITOS, TÉCNICOS E CONSULTORES, DE NACIONALIDADE ESTRANGEIRA, QUE EXERÇAM FUNÇÕES DE CARÁTER PERMANENTE - ART. 54 INCISO XII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "313", GRUPO = "ISENÇÃO", NM = "VEÍCULO DE FABRICAÇÃO NACIONAL ADQUIRIDO POR FUNCIONÁRIO DAS MISSÕES DIPLOMÁTICAS ACREDITADAS JUNTO AO GOVERNO BRASILEIRO - ART. 54 INCISO XIII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "314", GRUPO = "ISENÇÃO", NM = "PRODUTOS NACIONAIS SAÍDOS DIRETAMENTE PARA LOJAS FRANCAS - ART. 54 INCISO XIV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "315", GRUPO = "ISENÇÃO", NM = "MATERIAIS E EQUIPAMENTOS DESTINADOS A ITAIPU BINACIONAL - ART. 54 INCISO XV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "316", GRUPO = "ISENÇÃO", NM = "PRODUTOS IMPORTADOS POR MISSÕES DIPLOMÁTICAS, CONSULADOS OU ORGANISMO INTERNACIONAL - ART. 54 INCISO XVI DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "317", GRUPO = "ISENÇÃO", NM = "BAGAGEM DE PASSAGEIROS DESEMBARAÇADA COM ISENÇÃO DO II. - ART. 54 INCISO XVII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "318", GRUPO = "ISENÇÃO", NM = "BAGAGEM DE PASSAGEIROS DESEMBARAÇADA COM PAGAMENTO DO II. - ART. 54 INCISO XVIII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "319", GRUPO = "ISENÇÃO", NM = "REMESSAS POSTAIS INTERNACIONAIS SUJEITAS A TRIBUTAÇÃO SIMPLIFICADA. - ART. 54 INCISO XIX DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "320", GRUPO = "ISENÇÃO", NM = "MÁQUINAS E OUTROS DESTINADOS À PESQUISA CIENTÍFICA E TECNOLÓGICA - ART. 54 INCISO XX DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "321", GRUPO = "ISENÇÃO", NM = "PRODUTOS DE PROCEDÊNCIA ESTRANGEIRA, ISENTOS DO II CONFORME LEI Nº 8032/1990. - ART. 54 INCISO XXI DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "322", GRUPO = "ISENÇÃO", NM = "PRODUTOS DE PROCEDÊNCIA ESTRANGEIRA UTILIZADOS EM EVENTOS ESPORTIVOS - ART. 54 INCISO XXII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "323", GRUPO = "ISENÇÃO", NM = "VEÍCULOS AUTOMOTORES, MÁQUINAS, EQUIPAMENTOS, BEM ASSIM SUAS PARTES E PEÇAS SEPARADAS, DESTINADAS À UTILIZAÇÃO NAS ATIVIDADES DOS CORPOS DE BOMBEIROS - ART. 54 INCISO XXIII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "324", GRUPO = "ISENÇÃO", NM = "PRODUTOS IMPORTADOS PARA CONSUMO EM CONGRESSOS, FEIRAS E EXPOSIÇÕES - ART. 54 INCISO XXIV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "325", GRUPO = "ISENÇÃO", NM = "BENS DE INFORMÁTICA, MATÉRIA PRIMA, PRODUTOS INTERMEDIÁRIOS E EMBALAGEM DESTINADOS A URNAS ELETRÔNICAS - TSE - ART. 54 INCISO XXV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "326", GRUPO = "ISENÇÃO", NM = "MATERIAIS, EQUIPAMENTOS, MÁQUINAS, APARELHOS E INSTRUMENTOS, BEM ASSIM OS RESPECTIVOS ACESSÓRIOS, SOBRESSALENTES E FERRAMENTAS, QUE OS ACOMPANHEM, DESTINADOS À CONSTRUÇÃO DO GASODUTO BRASIL - BOLÍVIA - ART. 54 INCISO XXVI DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "327", GRUPO = "ISENÇÃO", NM = "PARTES, PEÇAS E COMPONENTES, ADQUIRIDOS POR ESTALEIROS NAVAIS BRASILEIROS, DESTINADOS AO EMPREGO NA CONSERVAÇÃO, MODERNIZAÇÃO, CONVERSÃO OU REPARO DE EMBARCAÇÕES REGISTRADAS NO REGISTRO ESPECIAL BRASILEIRO - REB - ART. 54 INCISO XXVII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "328", GRUPO = "ISENÇÃO", NM = "APARELHOS TRANSMISSORES E RECEPTORES DE RADIOTELEFONIA E RADIOTELEGRAFIA; VEÍCULOS PARA PATRULHAMENTO POLICIAL; ARMAS E MUNIÇÕES, DESTINADOS A ÓRGÃOS DE SEGURANÇA PÚBLICA DA UNIÃO, DOS ESTADOS E DO DISTRITO FEDERAL - ART. 54 INCISO XXVIII DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "329", GRUPO = "ISENÇÃO", NM = "AUTOMÓVEIS DE PASSAGEIROS DE FABRICAÇÃO NACIONAL DESTINADOS À UTILIZAÇÃO COMO TÁXI ADQUIRIDOS POR MOTORISTAS PROFISSIONAIS - ART. 55 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "330", GRUPO = "ISENÇÃO", NM = "AUTOMÓVEIS DE PASSAGEIROS DE FABRICAÇÃO NACIONAL DESTINADOS À UTILIZAÇÃO COMO TÁXI POR IMPEDIDOS DE EXERCER ATIVIDADE POR DESTRUIÇÃO, FURTO OU ROUBO DO VEÍCULO ADQUIRIDOS POR MOTORISTAS PROFISSIONAIS. - ART. 55 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "331", GRUPO = "ISENÇÃO", NM = "AUTOMÓVEIS DE PASSAGEIROS DE FABRICAÇÃO NACIONAL DESTINADOS À UTILIZAÇÃO COMO TÁXI ADQUIRIDOS POR COOPERATIVAS DE TRABALHO. - ART. 55 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "332", GRUPO = "ISENÇÃO", NM = "AUTOMÓVEIS DE PASSAGEIROS DE FABRICAÇÃO NACIONAL, DESTINADOS A PESSOAS PORTADORAS DE DEFICIÊNCIA FÍSICA, VISUAL, MENTAL SEVERA OU PROFUNDA, OU AUTISTAS - ART. 55 INCISO IV DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "333", GRUPO = "ISENÇÃO", NM = "PRODUTOS ESTRANGEIROS, RECEBIDOS EM DOAÇÃO DE REPRESENTAÇÕES DIPLOMÁTICAS ESTRANGEIRAS SEDIADAS NO PAÍS, VENDIDOS EM FEIRAS, BAZARES E EVENTOS SEMELHANTES POR ENTIDADES BENEFICENTES - ART. 67 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "334", GRUPO = "ISENÇÃO", NM = "PRODUTOS INDUSTRIALIZADOS NA ZONA FRANCA DE MANAUS - ZFM, DESTINADOS AO SEU CONSUMO INTERNO - ART. 81 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "335", GRUPO = "ISENÇÃO", NM = "PRODUTOS INDUSTRIALIZADOS NA ZFM, POR ESTABELECIMENTOS COM PROJETOS APROVADOS PELA SUFRAMA, DESTINADOS A COMERCIALIZAÇÃO EM QUALQUER OUTRO PONTO DO TERRITÓRIO NACIONAL - ART. 81 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "336", GRUPO = "ISENÇÃO", NM = "PRODUTOS NACIONAIS DESTINADOS À ENTRADA NA ZFM, PARA SEU CONSUMO INTERNO, UTILIZAÇÃO OU INDUSTRIALIZAÇÃO, OU AINDA, PARA SEREM REMETIDOS, POR INTERMÉDIO DE SEUS ENTREPOSTOS, À AMAZÔNIA OCIDENTAL - ART. 81 INCISO III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "337", GRUPO = "ISENÇÃO", NM = "PRODUTOS INDUSTRIALIZADOS POR ESTABELECIMENTOS COM PROJETOS APROVADOS PELA SUFRAMA, CONSUMIDOS OU UTILIZADOS NA AMAZÔNIA OCIDENTAL, OU ADQUIRIDOS ATRAVÉS DA ZFM OU DE SEUS ENTREPOSTOS NA REFERIDA REGIÃO - ART. 95 INCISO I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "338", GRUPO = "ISENÇÃO", NM = "PRODUTOS DE PROCEDÊNCIA ESTRANGEIRA, RELACIONADOS NA LEGISLAÇÃO, ORIUNDOS DA ZFM E QUE DEREM ENTRADA NA AMAZÔNIA OCIDENTAL PARA ALI SEREM CONSUMIDOS OU UTILIZADOS: - ART. 95 INCISO II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "339", GRUPO = "ISENÇÃO", NM = "PRODUTOS ELABORADOS COM MATÉRIAS-PRIMAS AGRÍCOLAS E EXTRATIVAS VEGETAIS DE PRODUÇÃO REGIONAL, POR ESTABELECIMENTOS INDUSTRIAIS LOCALIZADOS NA AMAZÔNIA OCIDENTAL, COM PROJETOS APROVADOS PELA SUFRAMA - ART. 95 INCISO III DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "340", GRUPO = "ISENÇÃO", NM = "PRODUTOS INDUSTRIALIZADOS EM ÁREA DE LIVRE COMÉRCIO - ART. 105 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "341", GRUPO = "ISENÇÃO", NM = "PRODUTOS NACIONAIS OU NACIONALIZADOS, DESTINADOS À ENTRADA NA ÁREA DE LIVRE COMÉRCIO DE TABATINGA - ALCT - ART. 107 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "342", GRUPO = "ISENÇÃO", NM = "PRODUTOS NACIONAIS OU NACIONALIZADOS, DESTINADOS À ENTRADA NA ÁREA DE LIVRE COMÉRCIO DE GUAJARÁ-MIRIM - ALCGM - ART. 110 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "343", GRUPO = "ISENÇÃO", NM = "PRODUTOS NACIONAIS OU NACIONALIZADOS, DESTINADOS À ENTRADA NAS ÁREAS DE LIVRE COMÉRCIO DE BOA VISTA - ALCBV E BONFIM - ALCB - ART. 113 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "344", GRUPO = "ISENÇÃO", NM = "PRODUTOS NACIONAIS OU NACIONALIZADOS, DESTINADOS À ENTRADA NA ÁREA DE LIVRE COMÉRCIO DE MACAPÁ E SANTANA - ALCMS - ART. 117 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "345", GRUPO = "ISENÇÃO", NM = "PRODUTOS NACIONAIS OU NACIONALIZADOS, DESTINADOS À ENTRADA NAS ÁREAS DE LIVRE COMÉRCIO DE BRASILÉIA - ALCB E DE CRUZEIRO DO SUL - ALCCS - ART. 120 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "346", GRUPO = "ISENÇÃO", NM = "RECOMPE - EQUIPAMENTOS DE INFORMÁTICA - DE BENEFICIÁRIO DO REGIME PARA ESCOLAS DAS REDES PÚBLICAS DE ENSINO FEDERAL, ESTADUAL, DISTRITAL, MUNICIPAL OU NAS ESCOLAS SEM FINS LUCRATIVOS DE ATENDIMENTO A PESSOAS COM DEFICIÊNCIA - DECRETO Nº 7.243/2010, ART. 7º" },
                    new MEnquadramento { ID = "347", GRUPO = "ISENÇÃO", NM = "RIO 2016 - IMPORTAÇÃO DE MATERIAIS PARA OS JOGOS (MEDALHAS, TROFÉUS, IMPRESSOS, BENS NÃO DURÁVEIS, ETC.) - LEI Nº 12.780/2013, ART. 4º, §1º, I" },
                    new MEnquadramento { ID = "348", GRUPO = "ISENÇÃO", NM = "RIO 2016 - SUSPENSÃO CONVERTIDA EM ISENÇÃO - LEI Nº 12.780/2013, ART. 6º, I" },
                    new MEnquadramento { ID = "349", GRUPO = "ISENÇÃO", NM = "RIO 2016 - EMPRESAS VINCULADAS AO CIO - LEI Nº 12.780/2013, ART. 9º, I, D" },
                    new MEnquadramento { ID = "350", GRUPO = "ISENÇÃO", NM = "RIO 2016 - SAÍDA DE PRODUTOS IMPORTADOS PELO RIO 2016 - LEI Nº 12.780/2013, ART. 10, I, D" },
                    new MEnquadramento { ID = "351", GRUPO = "ISENÇÃO", NM = "RIO 2016 - PRODUTOS NACIONAIS, NÃO DURÁVEIS, USO E CONSUMO DOS EVENTOS, ADQUIRIDOS PELAS PESSOAS JURÍDICAS MENCIONADAS NO § 2O DO ART. 4O DA LEI Nº 12.780/2013 - LEI Nº 12.780/2013, ART. 12" },
                    new MEnquadramento { ID = "601", GRUPO = "REDUÇÃO", NM = "EQUIPAMENTOS E OUTROS DESTINADOS À PESQUISA E AO DESENVOLVIMENTO TECNOLÓGICO - ART. 72 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "602", GRUPO = "REDUÇÃO", NM = "EQUIPAMENTOS E OUTROS DESTINADOS À EMPRESAS HABILITADAS NO PDTI E PDTA UTILIZADOS EM PESQUISA E AO DESENVOLVIMENTO TECNOLÓGICO - ART. 73 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "603", GRUPO = "REDUÇÃO", NM = "MICROCOMPUTADORES E OUTROS DE ATÉ R$11.000,00, UNIDADES DE DISCO, CIRCUITOS, ETC, DESTINADOS A BENS DE INFORMÁTICA OU AUTOMAÇÃO. CENTRO-OESTE SUDAM SUDENE - ART. 142, I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "604", GRUPO = "REDUÇÃO", NM = "MICROCOMPUTADORES E OUTROS DE ATÉ R$11.000,00, UNIDADES DE DISCO, CIRCUITOS, ETC, DESTINADOS A BENS DE INFORMÁTICA OU AUTOMAÇÃO. - ART. 142, I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "605", GRUPO = "REDUÇÃO", NM = "BENS DE INFORMÁTICA NÃO INCLUÍDOS NO ART. 142 DO DECRETO 7.212/2010 - PRODUZIDOS NO CENTRO-OESTE, SUDAM, SUDENE - ART. 143, I DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "606", GRUPO = "REDUÇÃO", NM = "BENS DE INFORMÁTICA NÃO INCLUÍDOS NO ART. 142 DO DECRETO 7.212/2010 - ART. 143, II DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "607", GRUPO = "REDUÇÃO", NM = "PADIS - ART. 150 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "608", GRUPO = "REDUÇÃO", NM = "PATVD - ART. 158 DO DECRETO 7.212/2010" },
                    new MEnquadramento { ID = "999", GRUPO = "OUTROS", NM = "TRIBUTAÇÃO NORMAL IPI; OUTROS; " },
                };
            }
        }

        public class MClasseEnquadramento
        {
            public string ID { get; set; }
            public string NM { get; set; }
        }

        public class MEnquadramento
        {
            public string ID { get; set; }
            public string GRUPO { get; set; }
            public string NM { get; set; }
        }
    }
}